[storage]
driver = "overlay"
runroot = "/run/user/1000/containers"
graphroot = "/home/casuki/VenvG_Native/podman-rootless"

[storage.options]
pull_options = {enable_partial_images = "false", use_hard_links = "false"}
